# Generated by Django 6.0.2 on 2026-02-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geeks', models.ImageField(upload_to='')),
            ],
        ),
    ]
